name: fake_store_app
description: Store App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/
    - assets/icons/

  fonts:
    - family: "Poppins"
      fonts:
        - asset: "assets/fonts/Poppins-Regular.ttf"
